#!/bin/sh

# This is just a wrapper, the real script is not part of the repository as
# it contains my passwords and username.
# To have your own data in the configuration after a checkout, do something 
# like
#
#   #!/bin/sh
#   sed 's/YOUR_ACTUAL_NICK/<nickname>/' |\
#   sed 's/ = "YOUR_ACTUAL_PASSWORD"/ = "<password>"/' |\
#   sed 's/ = "YOUR_ACTUAL_REALNAME"/ = "<realname>"/' |\
#   sed 's/ = "YOUR_ACTUAL_USERNAME"/ = "<username>"/'
#   #EOF
#
# in .git-filters/clean-passwords.real (the things written in caps must be
# adapted to your needs).
#

REPO="$(git rev-parse --show-toplevel)"
CLEAN_REAL="$REPO/.git-filters/clean-passwords.real"

if [ -x "$CLEAN_REAL" ]; then
    $CLEAN_REAL
else
    cat
fi
