#!/bin/sh

# This is just a wrapper, the real script is not part of the repository as
# it contains my passwords and username.
# To have your own data in the configuration after a checkout, do something 
# like
#
#   #!/bin/sh
#   sed 's/<nickname>/YOUR_ACTUAL_NICK/' |\
#   sed 's/ = "<password>"/ = "YOUR_ACTUAL_PASSWORD"/' |\
#   sed 's/ = "<realname>"/ = "YOUR_ACTUAL_REALNAME"/' |\
#   sed 's/ = "<username>"/ = "YOUR_ACTUAL_USERNAME"/'
#   #EOF
#
# in .git-filters/smudge-passwords.real (the things written in caps must be
# adapted to your needs).
#

REPO="$(git rev-parse --show-toplevel)"
SMUDGE_REAL="$REPO/.git-filters/smudge-passwords.real"

if [ -x "$SMUDGE_REAL" ]; then
    $SMUDGE_REAL
else
    cat
fi
